### PR TITLE
Update embedded-hal and add async support

### PR DESCRIPTION
**Pull request by umgefahren**
First of all: Thank you for this well written and well tested library.
A little nitpick: I think you could have reduced the lines of code by using some macros here and there, but otherwise great!

I updated the embedded-hal dependency to the probably soon released version 1.0. I also added async support, although we can only go to version 0.3.0, when the async_fn_in_trait feature becomes stable on 28th of December (https://releases.rs/docs/1.75.0/). There are doc comments missing from the async functions. Either we addd them later or we just link to the blocking version. The code is pretty much copy-paste anyway (sadly there is no real good way to build async agnostic apis).

Please leave feedback or critizism on my PR and have a great weak.

### CODE REVIEW

**Comment by umgefahren** [comment]
Please wait before merging. I can't test it on my device currently.

**Comment by umgefahren** [comment]
I tested it! Seems to work fine. I can't get the self test to work, but it didn't work with your code too.

**Comment by cfrenette** [comment]
Hi @umgefahren, I had been meaning to start the work to pick up embedded-hal 1.0 from upstream now that they are closer to release and it looks like you've done the work already, so thank you for putting in this work!

I haven't had time to review, but I'll set aside some time this weekend. In any case I don't think we'll merge into main until 1.0 is released (hopefully soon), so we can either continue the work here in this fork/PR or create a new branch tracking the embedded-hal RCs until 1.0.

**Comment by umgefahren** [comment]
Thank you, take your time. It will probably take until async fn in trait reaches stable rust.

**Comment by cfrenette** [comment]
Hi @umgefahren,

I created a branch for development against the embedded-hal 1.0 release. I pushed a commit to update to using the standard rustfmt settings. I was using non-standard formatting without including the settings .toml. I don't have any good reason to not use the defaults so to keep formatting consistent I'm okay with moving to the default.

Could you please rebase your PR on the new branch to clean up the commit history (separating the formatting changes from the actual changes). 

As for the actual substance of the changes, I think everything looks great. As you noticed my preference is to keep definitions obvious, often at the expense of having some (okay, maybe a lot) of boilerplate so I am a little uncertain about the macros in the return types for the Async methods, but I'm okay to stick with it for now.

If you rebase I'll merge this PR into the development branch and create issues to track the needed documentation and an example for async.

Lastly, regarding the self-test feature: I thought I had it working on my MCU (the NRF52833) but I won't have access to the hardware for a few weeks to see if I can reproduce. Feel free to open an issue with some details and I can take a look at it when I can hook up the hardware again.

Thanks again!

**Pull request closed without merging**
